version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  currency:
    lang: golang-middleware
    handler: ./currency
    image: ${IMAGE:-ghcr.io/${OWNER:-mrsimonemms}/openfaas-functions/currency:${TAG:-dev}}
