name: Build
on:
  - pull_request
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get faas-cli
        run: curl -sLSf https://cli.openfaas.com | sudo sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Pull templates
        run: |
          faas-cli template store pull golang-middleware

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v6
        with:
          strip_tag_prefix: v

      - name: Publish functions
        run: |
          OWNER="${{ github.actor }}"

          if [ "${{ steps.branch-name.outputs.is_tag }}" = "true"  ]; then
            TAG="${{ steps.branch-name.outputs.tag }}"

            TAG="${TAG}" OWNER="${OWNER}" faas-cli publish --extra-tag=latest --platforms=linux/amd64,linux/arm64,linux/arm/v7
          else
            TAG="branch-${{ steps.branch-name.outputs.current_branch }}"
            # Change "/" for "-"
            TAG="${TAG//\//-}"
            # Set to lowercase
            TAG="${TAG,,}"

            TAG="${TAG}" OWNER="${OWNER}" faas-cli publish --platforms linux/amd64
          fi
